---
title: "deisotoper cmp test data"
author: "Christian Panse"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Create Java MSM object

```{r echo=TRUE, warning=TRUE}
library(deisotoper)
#library(parallel)

input <- c("http://fgcz-ms.uzh.ch/~cpanse/R257544/TP_HeLa_200ng.RData",
  "http://fgcz-ms.uzh.ch/~cpanse/R257544/TP_HeLa_200ng_pd21.RData",
  "http://fgcz-ms.uzh.ch/~cpanse/R257544/TP_HeLa_200ng_msdeconv.RData")


S <- lapply(input, function(u){ 
  objN <- load(con <- url(u)); 
  jo <- jCreateMSM(get(objN)); 
  
  S <- jSummaryMSM(jo); 
  S$file <- objN;
  S$status <- 'input'
  
  Sd1 <- jSummaryMSM(jD <- deisotoper:::jDeisotopeMSM(jo, method="mspy"))
  Sd1$file <- objN;
  Sd1$status <- 'mspy'
  
  Sd2 <- jSummaryMSM(jD <- deisotoper:::jDeisotopeMSM(jo, method="fdbm"))
  Sd2$file <- objN;
  Sd2$status <- 'fdbm'
  
  # mgf(jGetMSM(jD), filename = paste("/tmp/", objN, ".mgf", sep=''))
  rbind(S, Sd1, Sd2)
  })


S <- do.call('rbind', S)
```

# summary plots

```{r fig.retina=3, fig.width=8, fig.height=5}
library(lattice)
filter <- (S$Attribute == "nr_of_peaks")
histogram(~Value | file * status, data=S[filter, ],
          scales = list(x=list(log=TRUE)), type='count')
```

```{r fig.retina=3, fig.width=8, fig.height=5}
filter <- (S$Attribute == "min_peak_distance")
histogram(~Value | file * status,  data=S[filter, ], 
          scales = list(x=list(log=TRUE)), type='count')
```


```{r fig.retina=3, fig.width=8, fig.height=5}
filter <- (S$Attribute == "max_peak_distance")
histogram(~Value | file * status,  data=S[filter, ],
          scales = list(x=list(log=TRUE)), type='count')
```


```{r fig.retina=3, fig.width=8, fig.height=5}
filter <- (S$Attribute == "sum_intensity")
histogram(~Value | file* status,  data=S[filter, ],
          scales = list(x=list(log=TRUE)), type='count')
```

```{r fig.retina=3, fig.width=8, fig.height=5}
filter <- (S$Attribute == "min_intensity")
histogram(~Value | file * status ,  data=S[filter, ],
          scales = list(x=list(log=TRUE)), type='count')
```


```{r fig.retina=3, fig.width=8, fig.height=5}
filter <- (S$Attribute == "max_intensity")
histogram(~Value | file * status,  data=S[filter, ], scales = list(x=list(log=TRUE)), type='count')
```