---
title: "Deisotoper: Isotopic Cluster Graphs"
author: "Lucas Schmidt"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Create DOT Graphs

```{r echo=TRUE, warning=TRUE}
library(deisotoper)
library(DiagrammeR)

input <- "http://fgcz-ms.uzh.ch/~cpanse/R257544/TP_HeLa_200ng.RData" #REMOVE AND USE PACKAGE LOAD

id <- c(1, 44, 10000, 10001);
index <- c(0, 0, 18, 18);

objN <- load(con <- url(input));
obj <- get(objN);

dot <-c();
  
for(i in 1:length(id)) {
  ms <- jCreateMS(obj[id[i]]);

  ims <- jCreateIMS(ms)

  dot <- c(dot, deisotoper::jGetDot(massspectrum = ms, isotopicmassspectrum = ims, index = index[i]));
}
```


# Display DOT Graphs

```{r fig.cap="Graph of mass spectrum 1, isotopic set 0"}
grViz(dot[1], width = 700)
```

```{r fig.cap="Graph of mass spectrum 44, isotopic set 0"}
grViz(dot[2], width = 700)
```

```{r fig.cap="Graph of mass spectrum 10000, isotopic set 18"}
grViz(dot[3], width = 700)
```

```{r fig.cap="Graph of mass spectrum 10001, isotopic set 18"}
grViz(dot[4], width = 700)
```