#!/bin/bash
RBENCHMARK="../R/rBenchmark.R"
MGF2RDATA="./mgf2RData.pl"

function benchmark() {
	in="$1"
	[ -e "$in" ] || exit 1

	out="${in%.*}_benchmark"
	tfile="temp.RData"

	rm -f "$tfile"
	"$MGF2RDATA" -n="${tfile%.*}" > /dev/null < "$in"
	[ -s "$tfile" ] || exit 1
	"$RBENCHMARK" "$tfile" "$out" > /dev/null
	rm -f "$tfile"
}

for i in "$@" 
do
	benchmark "$i"
done
