#R

#' Summary of a MSM object
#'
#' @param jobj a Java object reference generated by \code{\link{jCreateMSM}}.
#'
#' @return a \code{\link{data.frame}}
#' @export jSummaryMSM
#' @author Lucas Schmidt, Witold E. Wolski, Christian Panse
#' @importFrom utils read.csv
#' 
#' @seealso \code{\link{jCreateMSM}}
#' 
#' @examples
#' load(system.file("extdata",
#'    name='TP_HeLa_200ng_filtered_pd21.RData', package = "deisotoper"))
#'  joMSM <- jCreateMSM(TP_HeLa_200ng_filtered_pd21)
#'  X <- jSummaryMSM(joMSM)
#'  
#' par(mfrow=c(3,4)); 
#' rv <- lapply(unique(X$Attribute), 
#'  function(a){
#'    hist(X[X$Attribute == a, 3],xlab=a, main='Histgram')
#'    })
#' 
#' if(require(lattice)){
#' 
#' xyplot(Value ~ SpectrumID | Attribute,
#'  data=X, 
#'  pch='.')
#'
#'  xyplot(Value ~ SpectrumID | Attribute, data=X, scales = list(y=list(log=TRUE)))
#'    
#'    
#'  histogram(~Value | Attribute, data=X)
#'  histogram(~Value|Attribute, data=X, scales = list(x=list(log=TRUE)))
#'  histogram(~Value|Attribute, data=X, scales = list(x=list(log=TRUE)), type='count')
#' 
#'  bwplot(~Value | Attribute, data=X, scales = list(x = list(log = TRUE)))
#'  }

jSummaryMSM <- function(jobj){
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  sum <- .jnew("ch.fgcz.proteomics.R.DTOR")
  
  summary <- .jcall(sum, "S", "summaryR", jobj)
  con <- textConnection(summary)
  read.csv(con, sep=',', header = TRUE)
}

#' find index of nearest neighbor 
#'
#' @param q a double vector which can be considered as query objects.
#' @param vec a sorted double vector which can be considered as a data base.
#' @param check boolean enables test if \code{vec} is sorted. default is \code{FALSE}
#'
#' @description Given a vector of sorted double values \code{vec} of size
#' \code{n} and a vector of \code{m} query objects \code{q}.
#'
#' \code{findNN} determines for each element \code{q[i]} in \code{q}
#' the nearest neighbor index \code{o} so that the following remains true:
#'  
#'  there is no element \code{k} with \code{1} \eqn{\le} \code{k}
#' \eqn{\le} \code{n} and \code{k} is not \code{o} so that
#'
#' \code{abs(vec[k] - q[i])} < \code{abs(vec[o] - q[i])}.
#' 
#'  The internal algorithm of \code{findNN} is implemented as binary search.
#' \code{findNN} has \eqn{O(m * log(n))} time complexity.
#'
#' @author Christian Panse
#' @seealso \code{protViz::findNN}'s cpluplus implementation.
#' @return an integer vector 
#' @export findNN
#' 
#' @examples
#' 
#' 
#' (NNidx <- findNN(q<-c(1, 1.0001, 1.24, 1.26), DB<-seq(1,5,by=0.25)))
#' (NNidx == c(1,1,2,2))
#' 
#' # should be 0
#' unique(DB[findNN(DB,DB)] - DB)
#' 
#' 
findNN <- function (q, vec, check = FALSE) {
  .jinit()
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()

  jFindNN <- .jnew("ch.fgcz.proteomics.R.UtilitiesR")
  
  idx <- (.jcall(jFindNN, "[D", "findNNR", as.double(vec), as.double(q)) + 1)
}

#' Coerce to MS
#'
#' @param x 
#' @description Functions to check if an object is a MS, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export is.MS 
is.MS <- function(x){
  
  if (sum(c("title", "rtinseconds", "charge","scan","pepmass","mZ","intensity") %in% names(x)) != 7){
    warning('attributed check failed.')
    #return (FALSE)
  }
  
  if (!is.vector(x$mZ) || !is.numeric(x$mZ) || is.unsorted(x$mZ)){
    warning('mZ value check failed.')
    warning(x$mZ)
    return(FALSE)
  }
    
  if (!is.vector(x$intensity) || !is.numeric(x$intensity)){
    warning('intensity check failed.')
    return(FALSE)
  }
  
  if (!is.numeric(x$pepmass) || !is.numeric(x$rtinseconds) || !is.numeric(x$charge) || !is.numeric(x$id)){
     warning('pepmass, rtinseconds, ... check failed.')
     return (FALSE)
  }
  
  TRUE
}


#' Coerce to MSM
#'
#' @param x 
#' @description Functions to check if an object is a MSM, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export is.MSM
is.MSM <- function(x){
  rv <- sapply(x, function(y){
    if (!is.MS(y)){
      return (FALSE)
    }
    TRUE
  })
  sum(rv) ==  length(rv)
}

#' creates Mass Spectrometry Measurement (MSM) Java object 
#'
#' @param obj \code{protViz""psmSet} object
#'
#' @return returns a jcall object reference
#' 
#' @seealso \code{\link{jSummaryMSM}}
#' @import rJava
#' @export jCreateMSM
#' @author Lucas Schmidt, Witold E. Wolski, Christian Panse
#' @examples 
#' load(system.file("extdata",
#'    name='TP_HeLa_200ng_filtered_pd21.RData', package = "deisotoper"))
#' joMSM <- jCreateMSM(TP_HeLa_200ng_filtered_pd21)
#' 
#' 
#' \dontrun{
#'  mzXMLfilename <- system.file("extdata",
#'       name='20161010_04_TP_HeLa_200ng.mzXML', package = "deisotoper")
#'       
#'  jo <- jCreateMSM(as.psmSet.mzXML(openMSfile(mzXMLfilename)))
#' }
#' 
jCreateMSM <- function (obj) {
  
  
  src <- deparse(substitute(obj))
  
 
    obj <- as.MSM(obj)
 
  
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  DTOR <- .jnew("ch.fgcz.proteomics.R.DTOR")
  
  MSM <- .jcall(DTOR, "Lch/fgcz/proteomics/dto/MassSpectrometryMeasurement;", "massSpectrometryMeasurementR", src)
  
  lapply(obj, function(x) {
    if (is.null(x))
      {return (x)}
    if(!'id' %in% names(x)){
      x$id <- 0
    }
    
    if (!'title' %in% names(x)){
      x$title <- "xx"
    }
    
    .jcall(MSM, "V", "addMS", "MS2 Spectrum", x$title, x$mZ, x$intensity,
           x$pepmass, x$rtinseconds, as.integer(x$charge), as.integer(x$id))
  })
  
  MSM
}

#' Coerce to MS
#'
#' @param x 
#' @description Functions to check if an object is a MSM, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export as.MS
as.MS<- function(x){
  
  
  if ('mZ' %in% names(x) && length(x$mZ) < 2){
    return (NULL)
  }
  if (!('pepmass' %in% names(x)) || is.na(x$pepmass)){
    x$pepmass <- 100.0
  }
  
  if (!('title' %in% names(x)) || is.na(x$title) ){
    x$title <- "no title"
  }
  
  if (!('rtinseconds' %in% names(x)) || is.na(x$rtinseconds) ){
    x$rtinseconds <- 1
  }
  
  if ( !('charge' %in% names(x)) || is.na(x$charge) ){
    x$charge <- 1
  }
  
  if ( !('id' %in% names(x)) || is.na(x$id)){
    x$id <- 1
  }
  
  
  if(is.unsorted(x$mZ)){
    idx<-order(x$mZ)
    x$mZ <- x$mZ[idx]
    x$intensity <- x$intensity[idx]
  }
  
  stopifnot(is.MS(x))
  
  x
}

#' Coerce to MSM
#'
#' @param x 
#' @description Functions to check if an object is a MSM, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export as.MSM
as.MSM <-function(x){
  filter <- sapply(x, function(y){length(y$mZ) > 1})
  x <- lapply(x[filter], as.MS)
  stopifnot(is.MSM(x))
  x
}

#' Title
#'
#' @param jobj 
#'
#' @return
#' @export jGetMSM
#' @examples 
#' load(system.file("extdata",
#' name='TP_HeLa_200ng_filtered_pd21.RData', package = "deisotoper"))
#' joMSM <- jCreateMSM(TP_HeLa_200ng_filtered_pd21)
jGetMSM <- function(jobj) {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  source <- .jcall(jobj, "S", "getSource")
  
  MSlist <- .jcall(jobj, "Ljava/util/List;", "getMSlist")
  
  MSlistR <- rJava:::as.list.jobjRef(MSlist)
  
  MSM <- lapply(1: length(MSlistR), function(i){
    
    typ <- .jcall(MSlistR[[i]], "S", "getTyp")
    searchengine <- .jcall(MSlistR[[i]], "S", "getSearchEngine")
    id <- .jcall(MSlistR[[i]], "I", "getId")
    charge <- .jcall(MSlistR[[i]], "[I", "getChargeArray")
    isotope <- .jcall(MSlistR[[i]], "[D", "getIsotopeArray")
   
    
    
    list(mZ =.jcall(MSlistR[[i]], "[D", "getMzArray"),
         intensity = .jcall(MSlistR[[i]], "[D", "getIntensityArray"),
         rtinseconds = .jcall(MSlistR[[i]], "D", "getRt"),
         pepmass = .jcall(MSlistR[[i]], "D", "getPeptideMass"),
         id =  .jcall(MSlistR[[i]], "I", "getId"),
         charge = .jcall(MSlistR[[i]], "I", "getChargeState"),
         scans = .jcall(MSlistR[[i]], "I", "getId"),
         title = paste('deisotoped', i))
  }
  )
  
  as.MSM(MSM)
}

#' Serializes a MSM into a json.
#'
#' @param jobj
#' @param filename 
#'
#' @return
#' @export jWriteMSM2JSON
#'
#' @examples
#'
jWriteMSM2JSON <- function(jobj, filename='test.json'){
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jaddClassPath("inst/java/gson-2.8.1.jar")
  .jclassPath()
  Serialize <- .jnew("ch.fgcz.proteomics.R.DTOR")
  
  json <- .jcall(Serialize, "S", "serializeMSMToJsonR", filename, jobj)
  
  json
}

#' Deserializes a json into a MSM.
#'
#' @param filename 
#'
#' @return
#' @export jReadJSON2MSM
#'
#' @examples
#'
jReadJSON2MSM <- function(filename='test.json'){
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jaddClassPath("inst/java/gson-2.8.1.jar")
  .jclassPath()
  Serialize <- .jnew("ch.fgcz.proteomics.R.DTOR")
  
  MSM <- .jcall(Serialize, "Lch/fgcz/proteomics/dto/MassSpectrometryMeasurement;", "deserializeJsonToMSMR", filename)
  
  MSM
}

#' Returns Java version string
#'
#' @return
#' @export jVersionMSM
#'
jVersionMSM <- function() {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  MSM <- .jnew("ch.fgcz.proteomics.R.DTOR")
  
  version <- .jcall(MSM, "S", "versionR")
  
  version
}

#' Deisotopes a MSM.
#'
#' @return
#' @export jDeisotopeMSM
#'
#' @examples
#'
#' load(system.file("extdata", name='TP_HeLa_200ng_filtered_pd21.RData', package = "deisotoper"))
#' joMSM <- jCreateMSM(TP_HeLa_200ng_filtered_pd21)
#'
#' joMSMdeisotoped <- jDeisotopeMSM(joMSM)
#'
#' joMSMsummary <- jSummaryMSM(joMSM)
#' joMSMdeisotopedsummary <- jSummaryMSM(joMSMdeisotoped)
#' 
jDeisotopeMSM <- function(jobj, modus="first", configfile="nofile", percent=0, errortolerance=0.3, delta = 0.003) {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jaddClassPath("inst/java/antlr4-runtime-4.5.3.jar")
  .jaddClassPath("inst/java/jgraph-5.13.0.0.jar")
  .jaddClassPath("inst/java/jgrapht-core-1.0.1.jar")
  .jaddClassPath("inst/java/jgrapht-demo-1.0.1.jar")
  .jaddClassPath("inst/java/jgrapht-ext-1.0.1.jar")
  .jaddClassPath("inst/java/jgrapht-ext-1.0.1-uber.jar")
  .jaddClassPath("inst/java/jgraphx-2.0.0.1.jar")
  .jclassPath()
  
  String <- J("java.lang.String")
  m <- new( String, modus )
  aamass <- new( String, configfile )
  
  d <- .jnew("ch.fgcz.proteomics.R.FDBMR")
  
  output <- .jcall(d, "Lch/fgcz/proteomics/dto/MassSpectrometryMeasurement;", "deisotopeMSMR", jobj, m, aamass, percent, errortolerance, delta)
  
  output
}

#' Deisotopes a MS.
#'
#' @return
#' @export jDeisotopeMS
#'
#' @examples
#' 
#' load(system.file("extdata", name='TP_HeLa_200ng_filtered_pd21.RData', package = "deisotoper"))
#' joMSM <- jCreateMSM(TP_HeLa_200ng_filtered_pd21)
#' 
#' mslist<-joMSM$getMSlist()
#' ms <- mslist$get(as.integer(0)) #index 0 of joMSM
#' 
#' msdeisotoped <- jDeisotopeMS(ms)
#' 
jDeisotopeMS <- function(ms, modus="first", configfile="nofile", percent=0, errortolerance = 0.3, delta = 0.003) {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jaddClassPath("inst/java/antlr4-runtime-4.5.3.jar")
  .jaddClassPath("inst/java/jgraph-5.13.0.0.jar")
  .jaddClassPath("inst/java/jgrapht-core-1.0.1.jar")
  .jaddClassPath("inst/java/jgrapht-demo-1.0.1.jar")
  .jaddClassPath("inst/java/jgrapht-ext-1.0.1.jar")
  .jaddClassPath("inst/java/jgrapht-ext-1.0.1-uber.jar")
  .jaddClassPath("inst/java/jgraphx-2.0.0.1.jar")
  .jclassPath()
  
  String <- J("java.lang.String")
  m <- new( String, modus )
  aamass <- new( String, configfile )
  
  d <- .jnew("ch.fgcz.proteomics.R.FDBMR")
  
  config <- .jnew("ch.fgcz.proteomics.fdbm.ScoreConfig", configfile)
  
  output <- .jcall(d, "Lch/fgcz/proteomics/dto/MassSpectrum;", "deisotopeMSR", ms, m, config, percent, errortolerance, delta)
  
  output
}

#' Used for benchmarking. The input is a RData and the output is also a MGF.
#' 
#' @return
#' @export jBenchmark
#' 
jBenchmark <- function(input, output, save=FALSE, modus="first", configfile="nofile", percent=0, errortolerance = 0.3, delta = 0.003) {
  name <- load(file = input)
  mgf(jGetMSM(deisotoper:::jDeisotopeMSMfdbm(jobj = jCreateMSM(get(name)), modus = modus, save = save, configfile = configfile, percent = percent, errortolerance = errortolerance, delta = delta)), filename = output)
}

jCreateIMS <- function(massspectrum, errortolerance = 0.3, configfile = "nofile") {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  adapter <- .jnew("ch.fgcz.proteomics.R.FDBMR")
  
  ims <- .jcall(adapter, "Lch/fgcz/proteomics/fdbm/IsotopicMassSpectrum;", "getIMS", massspectrum, errortolerance, configfile)
  
  ims
}

jGetDotGraphFromIS <- function(isotopicset) {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  adapter <- .jnew("ch.fgcz.proteomics.R.FDBMR")
  
  dot <- .jcall(adapter, "S", "getGraphFromIS", isotopicset)
  
  dot
}

jGetIS <- function(isotopicmassspectrum, index) {
  islist <- ims$getIsotopicMassSpectrum()
  is <- islist$get(as.integer(index))
  
  is
}

jGetDot <- function(isotopicmassspectrum, index) {
  dot <- jGetIS(isotopicmassspectrum = isotopicmassspectrum, index = index)
  
  dot
}

jGetMS <- function(massspectrum) {
  MS <- c(typ <- .jcall(massspectrum, "S", "getTyp"),
  searchengine = searchengine <- .jcall(massspectrum, "S", "getSearchEngine"),
  id = id <- .jcall(massspectrum, "I", "getId"),
  charge = charge <- .jcall(massspectrum, "[I", "getChargeArray"),
  isotope = isotope <- .jcall(massspectrum, "[D", "getIsotopeArray"),
  list(mZ =.jcall(massspectrum, "[D", "getMzArray"),
       intensity = .jcall(massspectrum, "[D", "getIntensityArray"),
       rtinseconds = .jcall(massspectrum, "D", "getRt"),
       pepmass = .jcall(massspectrum, "D", "getPeptideMass"),
       id =  .jcall(massspectrum, "I", "getId"),
       charge = .jcall(massspectrum, "I", "getChargeState"),
       scans = .jcall(massspectrum, "I", "getId"),
       title = "MassSpectrum')")
  )
  
  as.MS(MS)
}