#R

#' Summary of a MSM object
#'
#' @param jobj a Java object reference generated by \code{\link{jCreateMSM}}.
#'
#' @return a \code{\link{data.frame}}
#' @export jSummaryMSM
#' @author Lucas Schmidt, Witold E. Wolski, Christian Panse
#' @importFrom utils read.csv
#' 
#' @seealso \code{\link{jCreateMSM}}
#' 
#' @examples
#' load(system.file("extdata",
#'    name='TP_HeLa_200ng_filtered_pd21.RData', package = "deisotoper"))
#'  joMSM <- jCreateMSM(TP_HeLa_200ng_filtered_pd21)
#'  X <- jSummaryMSM(joMSM)
#'  
#' par(mfrow=c(3,4)); 
#' rv <- lapply(unique(X$Attribute), 
#'  function(a){
#'    hist(X[X$Attribute == a, 3],xlab=a, main='Histgram')
#'    })
#' 
#' if(require(lattice)){
#' 
#' xyplot(Value ~ SpectrumID | Attribute,
#'  data=X, 
#'  pch='.')
#'
#'  xyplot(Value ~ SpectrumID | Attribute, data=X, scales = list(y=list(log=TRUE)))
#'    
#'    
#'  histogram(~Value | Attribute, data=X)
#'  histogram(~Value|Attribute, data=X, scales = list(x=list(log=TRUE)))
#'  histogram(~Value|Attribute, data=X, scales = list(x=list(log=TRUE)), type='count')
#' 
#'  bwplot(~Value | Attribute, data=X, scales = list(x = list(log = TRUE)))
#'  }

jSummaryMSM <- function(jobj){
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  sum <- .jnew("ch.fgcz.proteomics.dto.Summary")
  
  summary <- .jcall(sum, "S", "makeSummary", jobj)
  con <- textConnection(summary)
  read.csv(con, sep=',', header = TRUE)
}

#' find index of nearest neighbor 
#'
#' @param q a double vector which can be considered as query objects.
#' @param vec a sorted double vector which can be considered as a data base.
#' @param check boolean enables test if \code{vec} is sorted. default is \code{FALSE}
#'
#' @description Given a vector of sorted double values \code{vec} of size
#' \code{n} and a vector of \code{m} query objects \code{q}.
#'
#' \code{findNN} determines for each element \code{q[i]} in \code{q}
#' the nearest neighbor index \code{o} so that the following remains true:
#'  
#'  there is no element \code{k} with \code{1} \eqn{\le} \code{k}
#' \eqn{\le} \code{n} and \code{k} is not \code{o} so that
#'
#' \code{abs(vec[k] - q[i])} < \code{abs(vec[o] - q[i])}.
#' 
#'  The internal algorithm of \code{findNN} is implemented as binary search.
#' \code{findNN} has \eqn{O(m * log(n))} time complexity.
#'
#' @author Christian Panse
#' @seealso \code{protViz::findNN}'s cpluplus implementation.
#' @return an integer vector 
#' @export findNN
#' 
#' @examples
#' 
#' 
#' (NNidx <- findNN(q<-c(1, 1.0001, 1.24, 1.26), DB<-seq(1,5,by=0.25)))
#' (NNidx == c(1,1,2,2))
#' 
#' # should be 0
#' unique(DB[findNN(DB,DB)] - DB)
#' 
#' 
findNN <- function (q, vec, check = FALSE) {
  .jinit()
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()

  jFindNN <- .jnew("ch.fgcz.proteomics.utilities.FindNN")
  
  .jcall(jFindNN, "V", "setVec", as.double(vec))
  .jcall(jFindNN, "V", "setQ", as.double(q))
  
  idx <- (.jcall(jFindNN, "[D", "getIndex") + 1)
}


#' Coerce to MS
#'
#' @param x 
#' @description Functions to check if an object is a MS, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export is.MS 
is.MS <- function(x){
  
  if (sum(c("title", "rtinseconds", "charge","scan","pepmass","mZ","intensity") %in% names(x)) != 7){
    warning('attributed check failed.')
    return (FALSE)
  }
  
  if (!is.vector(x$mZ) || !is.numeric(x$mZ) || is.unsorted(x$mZ)){
    warning('mZ value check failed.')
    warning(x$mZ)
    return(FALSE)
  }
    
  if (!is.vector(x$intensity) || !is.numeric(x$intensity)){
    warning('intensity check failed.')
    return(FALSE)
  }
  
  if (!is.numeric(x$pepmass) || !is.numeric(x$rtinseconds) || !is.numeric(x$charge) || !is.numeric(x$id)){
     warning('pepmass, rtinseconds, ... check failed.')
     return (FALSE)
  }
  
  TRUE
}


#' Coerce to MSM
#'
#' @param x 
#' @description Functions to check if an object is a MSM, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export is.MSM
is.MSM <- function(x){
  rv <- sapply(x, function(y){
    if (!is.MS(y)){
      return (FALSE)
    }
    TRUE
  })
  sum(rv) ==  length(rv)
}

#' creates Mass Spectrometry Measurement (MSM) Java object 
#'
#' @param obj \code{protViz""psmSet} object
#'
#' @return returns a jcall object reference
#' 
#' @seealso \code{\link{jSummaryMSM}}
#' @import rJava
#' @export jCreateMSM
#' @author Lucas Schmidt, Witold E. Wolski, Christian Panse
#' @examples 
#' load(system.file("extdata",
#'    name='TP_HeLa_200ng_filtered_pd21.RData', package = "deisotoper"))
#' joMSM <- jCreateMSM(TP_HeLa_200ng_filtered_pd21)
#' 
#' 
#' \dontrun{
#'  mzXMLfilename <- system.file("extdata",
#'       name='20161010_04_TP_HeLa_200ng.mzXML', package = "deisotoper")
#'       
#'  jo <- jCreateMSM(as.psmSet.mzXML(openMSfile(mzXMLfilename)))
#' }
#' 
jCreateMSM <- function (obj) {
  
  
  src <- deparse(substitute(obj))
  
 
    obj <- as.MSM(obj)
 
  
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  MSM <- .jnew("ch.fgcz.proteomics.dto.MassSpectrometryMeasurement", src)
  
  lapply(obj, function(x) {
    if (is.null(x))
      {return (x)}
    if(!'id' %in% names(x)){
      x$id <- 0
    }
    
    if (!'title' %in% names(x)){
      x$title <- "xx"
    }
    
    .jcall(MSM, "V", "addMS", "MS2 Spectrum", x$title, x$mZ, x$intensity,
           x$pepmass, x$rtinseconds, as.integer(x$charge), as.integer(x$id))
  })
  
  MSM
}

#' Coerce to MS
#'
#' @param x 
#' @description Functions to check if an object is a MSM, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export as.MS
as.MS<- function(x){
  
  
  if ('mZ' %in% names(x) && length(x$mZ) < 2){
    return (NULL)
  }
  if (!('pepmass' %in% names(x)) || is.na(x$pepmass)){
    x$pepmass <- 100.0
  }
  
  if (!('title' %in% names(x)) || is.na(x$title) ){
    x$title <- "no title"
  }
  
  if (!('rtinseconds' %in% names(x)) || is.na(x$rtinseconds) ){
    x$rtinseconds <- 1
  }
  
  if ( !('charge' %in% names(x)) || is.na(x$charge) ){
    x$charge <- 1
  }
  
  if ( !('id' %in% names(x)) || is.na(x$id)){
    x$id <- 1
  }
  
  
  if(is.unsorted(x$mZ)){
    idx<-order(x$mZ)
    x$mZ <- x$mZ[idx]
    x$intensity <- x$intensity[idx]
  }
  
  stopifnot(is.MS(x))
  
  x
}

#' Coerce to MSM
#'
#' @param x 
#' @description Functions to check if an object is a MSM, or coerce it if possible.
#' @return \code{TRUE} or \code{FALSE}
#' @export as.MSM
as.MSM <-function(x){
  filter <- sapply(x, function(y){length(y$mZ) > 1})
  x <- lapply(x[filter], as.MS)
  stopifnot(is.MSM(x))
  x
}
  

jGetMSM <- function(jobj) {
  
}

jWriteMSM2JSON <- function(jobj, filename='test.json'){
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jaddClassPath("inst/java/gson-2.8.1.jar")
  .jclassPath()
  Serialize<- .jnew("ch.fgcz.proteomics.dto.Serialize")
  
  json <- .jcall(Serialize, "S", "serializeMSMToJson", filename, jobj)
  
  json
}

jReadJSON2MSM <- function(filename='test.json'){
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jaddClassPath("inst/java/gson-2.8.1.jar")
  .jclassPath()
  Serialize <- .jnew("ch.fgcz.proteomics.dto.Serialize")
  
  MSM <- .jcall(Serialize, "Lch/fgcz/proteomics/dto/MassSpectrometryMeasurement;", "deserializeJsonToMSM", filename)
  
  MSM
}

#' Returns Java version string
#'
#' @return
#' @export jVersionMSM
#'
#' @examples
jVersionMSM <- function() {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  MSM <- .jnew("ch.fgcz.proteomics.dto.MassSpectrometryMeasurement", " ")
  
  version <- .jcall(MSM, "S", "version")
  
  version
}

jDeisotopeMSM <- function(jobj) {
  .jinit(parameters = "-XX:-UseGCOverheadLimit")
  .jaddClassPath("inst/java/deisotoper.jar")
  .jclassPath()
  
  d <- .jnew("ch.fgcz.proteomics.mspy.Deisotope")
  
  output <- .jcall(d, "Lch/fgcz/proteomics/dto/MassSpectrometryMeasurement;", "deisotopeMSM", jobj)
  
  output
}
